[package]
name = "Athena"
version = "0.1.0"
edition = "2024"

[dependencies]
aegis_athena_contracts = { git = "https://github.com/ARelaxedScholar/Aegis-Athena-Contracts" }
aegis = { git = "https://github.com/ARelaxedScholar/Aegis"}
